baseurl = "tjbarbour.com"
title = "T.J. Barbour"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license.."


[author]
    name = "T.J. Barbour"
[params]
  DateForm = "Mon, Jan 2, 2006"
  Author = "T.J. Barbour"
  email = "tjbarbour@gmail.com"
  Ganalytics = "XX-00000000-0"
  Description = "Software Developer focused on UX / Web / .net"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/tjbarbour"
[[params.social]]
    title = "github"
    url = "https://github.com/tjbarbour"
[[params.social]]
    title = "stack-overflow"
    url = "http://stackoverflow.com/users/37207/tjb"

[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/tjbarbour"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
 [[menu.main]]
  name = "About"
  url = "/about"
  weight = -180
  [[menu.main]]
  name = "Resume"
  url = "https://dl.dropboxusercontent.com/u/4111188/TJ-Barbour-Resume.pdf"
  weight = -180